version: '3.8'

services:
  web:
    image: frontend:1.0
    ports:
      - "80:80"
    networks:
      - projekt-network

  backend:
    image: backend:1.1
    ports:
      - "3001:3001"
    networks:  
      - projekt-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: nimda
      MONGO_URI: mongodb://admin:nimda@mongo:27017/testdb?authSource=admin

  mongo:
    image: mongo:1.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: nimda
    ports:
      - "27017:27017"
    networks:
      - projekt-network
networks:
  projekt-network:

